export const Symbols = {
  Config: 'Config',
  // Adapters
  Dialog: 'Dialog',
  Screen: 'Screen',
  ProcessMain: 'ProcessMain',
  KeysListener: 'KeysListener',
  FileManager: 'FileManager',
  // Repositories
  ComicRepository: 'ComicRepository',
  ShortcutsRepository: 'ShortcutsRepository',
  ScreenRepository: 'ScreenRepository',
  // Services
  ShowInfoShortcutsService: 'ShowInfoShortcutsService',
  RegisterShortcutsService: 'RegisterShortcutsService',
  SelectFileService: 'SelectFileService',
  OpenFileService: 'OpenFileService',
  // Listeners
  SelectFileListener: 'SelectFileListener',
  OpenFileListener: 'OpenFileListener',
  ShowInfoShortcutsListener: 'ShowInfoShortcutsListener',
  ToggleFullscreenListener: 'ToggleFullscreenListener',
  // UseCases
  ShowInfoShortcutsUseCase: 'ShowInfoShortcutsUseCase',
  RegisterShortcutsUseCase: 'RegisterShortcutsUseCase',
  ToggleFullscreenUseCase: 'ToggleFullscreenUseCase',
  SelectFileUseCase: 'SelectFileUseCase',
  OpenFileUseCase: 'OpenFileUseCase',
  ClearTmpFolder: 'ClearTmpFolder',
  // Utils
  RemoveFolder: 'RemoveFolder',
}
