export const Symbols = {
  Config: 'Config',
  // Adapters
  Dialog: 'Dialog',
  Screen: 'Screen',
  ProcessMain: 'ProcessMain',
  KeysListener: 'KeysListener',
  FileManager: 'FileManager',
  FileSystem: 'FileSystem',
  // Repositories
  ComicRepository: 'ComicRepository',
  ShortcutsRepository: 'ShortcutsRepository',
  ScreenRepository: 'ScreenRepository',
  SettingsRepository: 'SettingsRepository',
  // Services
  ShowInfoShortcutsService: 'ShowInfoShortcutsService',
  RegisterShortcutsService: 'RegisterShortcutsService',
  SelectFileService: 'SelectFileService',
  SelectDirectoryService: 'SelectDirectoryService',
  UpdateSettingsService: 'UpdateSettingsService',
  ReadSettingsFileService: 'ReadSettingsFileService',
  WriteSettingsFileService: 'WriteSettingsFileService',
  OpenComicService: 'OpenFileService',
  // Listeners
  SelectFileListener: 'SelectFileListener',
  SelectDirectoryListener: 'SelectDirectoryListener',
  OpenFileListener: 'OpenFileListener',
  ShowInfoShortcutsListener: 'ShowInfoShortcutsListener',
  ToggleFullscreenListener: 'ToggleFullscreenListener',
  UpdateSettingsListener: 'UpdateSettingsListener',
  SettingsChangeListener: 'SettingsChangeListener',
  // UseCases
  ShowInfoShortcutsUseCase: 'ShowInfoShortcutsUseCase',
  RegisterShortcutsUseCase: 'RegisterShortcutsUseCase',
  ToggleFullscreenUseCase: 'ToggleFullscreenUseCase',
  SelectFileUseCase: 'SelectFileUseCase',
  SelectDirectoryUseCase: 'SelectDirectoryUseCase',
  OpenComicUseCase: 'OpenFileUseCase',
  ClearTmpFolder: 'ClearTmpFolder',
  // Utils
  RemoveFolder: 'RemoveFolder',
  ReadFolder: 'ReadFolder',
  NormalizeAssetSrc: 'NormalizeAssetSrc'
}
